### ISSUE TITLE
New versions of node break the build

### ISSUE THREAD

**Issue by grandafrato** [gjaldon/heroku-buildpack-phoenix-static#112]
When I tried building with node js 1.14+ i got this error:
```
/tmp/codon/tmp/buildpacks/046a7dbb0bd21772e3b9d262d0fbe72be102671d/lib/build.sh: line 29: fail_bin_install: command not found
```
And the whole deployment would fail.
However, when I used version 10.20.1 (because that's the version used in the phoenix docs) it just suddenly did work. I did not test for any versions in between that one and 1.14.0

**Comment by AaronJamesKing** [comment]
I also had a problem with a newer Node version (12.15.0):

```
...
-----> Phoenix app detected
-----> Loading configuration and environment
       Loading config...
       Detecting assets directory
       WARNING: no package.json detected in root nor custom directory
       * assuming phoenix 1.3.x and later, please check config file
       Will use phoenix configuration:
       * assets path assets
       * mix tasks namespace phx
       Will use the following versions:
       * Node 12.15.0
       Will export the following config vars:
DATABASE_URL
POOL_SIZE
SECRET_KEY_BASE
       * MIX_ENV=prod
-----> Installing binaries
Resolving node version 12.15.0...
Downloading and installing node 12.15.0...
       Installing Node 12.15.0...
       Using default npm version 6.13.4
-----> Building dependencies
       Installing node modules
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! invalid bin entry for package @babel/parser@7.12.17. key=parser, value=bin/babel-parser.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-02-21T01_45_52_394Z-debug.log
 !     Push rejected, failed to compile Phoenix app.
 !     Push failed
```

Fixed and successfully deployed using Node 10.20.1

**Comment by canelle20214** [comment]
Same problem here with a deployment using Heroku. 
npm `6.14.13`
and yarn `1.22.11`
```
 -----> Installing binaries
remote: Resolving node version 6.14.13...
remote: /tmp/codon/tmp/buildpacks/e1ebc0ce039e2d6d22ca731aebc3580cbde46136/lib/build.sh: line 28: fail_bin_install: command not found
remote:  !     Push rejected, failed to compile Phoenix app.
```

**Comment by jaimeiniesta** [comment]
This is suddenly failing for me, I hadn't done any change to the config and had been able to deploy just fine, with Node 14, but then I started getting:

```
remote: /tmp/codon/tmp/buildpacks/046a7dbb0bd21772e3b9d262d0fbe72be102671d/lib/build.sh: line 29: fail_bin_install: command not found
```

I have tried upgrading the Heroku stack, and also to the latest versions of Node and NPM in my `phoenix_static_buildpack.config` like:

```
node_version=20.2.0
npm_version=9.6.6
clean_cache=true
```

But I still get that error:

```
remote: -----> Installing binaries
remote:        clean_cache option set to true.
remote:        Cleaning out cache contents
remote:        Cleaning up old Node v14.13.0
remote: Resolving node version 20.2.0...
remote: /tmp/codon/tmp/buildpacks/046a7dbb0bd21772e3b9d262d0fbe72be102671d/lib/build.sh: line 29: fail_bin_install: command not found
remote:  !     Push rejected, failed to compile Phoenix app.
```

I double-checked and [Node 20.2.0 is available in Heroku](https://devcenter.heroku.com/changelog-items/2594). I also tried with 20.1.0 and also fails.

**Comment by pankamyk** [comment]
I've encountered the same issue just now. No changes to buildpack config/node versions, but suddenly it keeps failing. Same error as everyone else. Npm/node versions:
```
node_version=13.14.0
npm_version=6.14
```

**Comment by jaimeiniesta** [comment]
Thanks for the confirmation @pankamyk - I've submitted a ticket to Heroku.

**Comment by kkenan** [comment]
We're experiencing same issue here.

It seems it fails on this line https://github.com/gjaldon/heroku-buildpack-phoenix-static/blob/master/lib/build.sh#LL28C30-L28C176 and it looks like https://nodebin.herokai.com is down.
```
curl --verbose --data-urlencode "range=18.16.0" "https://nodebin.herokai.com/v1/node/linux-x64/latest.txt"
```

**Comment by pankamyk** [comment]
I can confirm that it looks like the root of this problem lies in the `nodebin.herokai.com` service. Some issue with SSL
```
# curl -get "https://nodebin.herokai.com/v1/node/linux-x64/latest.txt"
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to nodebin.herokai.com:443
```

**Comment by mracos** [comment]
FYI, before forking myself found out that [gigalixir's fork](https://github.com/gigalixir/gigalixir-buildpack-phoenix-static/commit/414e2fcabf0ac28ee5d63d588feff4afa6517ea2) fixed it 😄

**Comment by jaimeiniesta** [comment]
Cool @mracos - I can confirm that deploys work fine with Gigalixir's fork 👍

**Comment by joshwlewis** [comment]
Hi - Heroku did run a brownout on nodebin.herokai.com. Heroku has removed all dependencies on that service and hasn't used it internally for 4 years. The service will be decommissioned very soon. I'd heavily suggest removing the dependency from this buildpack. [Gigalixir's fork](https://github.com/gigalixir/gigalixir-buildpack-phoenix-static/commit/414e2fcabf0ac28ee5d63d588feff4afa6517ea2) will likely work as a short term fix, though keep in mind that both are very old forks of https://github.com/heroku/heroku-buildpack-nodejs, so I'd suggest using the latter if possible.

**Comment by jaimeiniesta** [comment]
Heroku informed me that the URL https://nodebin.herokai.com/ works again now.

Still, thanks for the warning that it will be decommissioned soon @joshwlewis - let's remove that dependency.

**Comment by WillRochaThomas** [comment]
Same issue started happening for me today, I when I run the same command as mentioned above I also see 

```
 # curl -get "https://nodebin.herokai.com/v1/node/linux-x64/latest.txt"
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to nodebin.herokai.com:443
```

**Comment by edmorley** [comment]
See:
https://devcenter.heroku.com/changelog-items/2598

**Comment by jaimeiniesta** [comment]
Using Gigalixir's fork instead of this buildpack works fine.

**Comment by kaikuchn** [comment]
> Hi - Heroku did run a brownout on nodebin.herokai.com. Heroku has removed all dependencies on that service and hasn't used it internally for 4 years. The service will be decommissioned very soon. I'd heavily suggest removing the dependency from this buildpack. [Gigalixir's fork](https://github.com/gigalixir/gigalixir-buildpack-phoenix-static/commit/414e2fcabf0ac28ee5d63d588feff4afa6517ea2) will likely work as a short term fix, though keep in mind that both are very old forks of https://github.com/heroku/heroku-buildpack-nodejs, so I'd suggest using the latter if possible.

Sadly the official buildpack only supports projects with a root-level package.json. There's a dirty hack to fix this but it ain't pretty.
I.e. this would require much more work than just switching them out and changing some config.

**Comment by WillRochaThomas** [comment]
> Using Gigalixir's fork instead of this buildpack works fine.

It does but that is obviously a very temporary fix as others have pointed out. I'd be open to contributing to updates for this buildpack, but I think it'd be really helpful to have some contributing guidelines on the repository if anyone who's worked on it before is happy to put those together?

**Comment by pankamyk** [comment]
Is this buildpack even maintained anymore?

**Comment by linomassarani** [comment]
Same problem here.

My use case is to document the process of deploying a legacy application on Heroku, in case someone wants to use it in the future, as we are planning to shut it down. 

For simplicity, I’m using only `HashNuke/heroku-buildpack-elixir` with the following configuration:

elixir_buildpack.config
```env
elixir_version=1.12.3
erlang_version=24.2
runtime_path=/app
hook_pre_fetch_dependencies="./pre_fetch_dependencies.sh"
hook_post_compile="./post_compile.sh"
```

pre_fetch_dependencies.sh
```sh
#!/bin/bash

echo "-----> Configuring Oban auth"
mix hex.repo add oban https://getoban.pro/repo \
  --fetch-public-key $OBAN_KEY_FINGERPRINT \
  --auth-key $OBAN_LICENSE_KEY
```

post_compile.sh
```sh
#!/bin/bash

echo "-----> Installing Node.js"
build_dir=$(ls -d /tmp/build_* | head -n 1)
node_version=14.15.4
node_name=node-v$node_version-linux-x64
node_tar_gz="$node_name.tar.gz"
node_url="https://nodejs.org/dist/v$node_version/$node_tar_gz"
curl $node_url -L --silent --fail --retry 5 --retry-max-time 15 -o /tmp/$node_tar_gz
tar xzf /tmp/$node_tar_gz -C /tmp
mkdir -p $build_dir/.heroku/node
mv /tmp/$node_name/* $build_dir/.heroku/node
node_bin_directory_path=$build_dir/.heroku/node/bin
chmod +x $node_bin_directory_path/*
PATH=$node_bin_directory_path:$PATH

echo "-----> Installing Node.js dependencies"
cd $build_dir/apps/umbrella_app_name/assets
npm install --quiet --unsafe-perm

echo "-----> Building Phoenix static assets"
npm run deploy

echo "-----> Cleaning up"
rm -rf $build_dir/apps/umbrella_app_name/assets/node_modules
```

.profile
```sh
#!/bin/bash

echo "-----> Making node binaries available for runtime environment"
PATH=$HOME/.heroku/node/bin:$PATH
```
